version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    rebase-strategy: 'auto'
    versioning-strategy: 'increase'
    labels:
      - 'dependencies'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'monthly'
    allowed:
      - dependency-type: 'all'
    labels:
      - 'docker'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'github-actions'
