version: '3.8'

services:
  app:
    build:
      context: .
      target: deps
    command: npm run dev
    volumes:
      - ./:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - .env.development
